[project]
name = "vllm-over-ip"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "transformers>=4.50.3",
    "vllm>=0.8.2",
    "iroh_py @ git+ssh://git@github.com/primeintellect-ai/iroh_py.git@a747724",
]
